import { ComparisonResult, Mismatch, MarkdownReport, JSONReport } from "./types";

/**
 * Generate Markdown ticket format
 */
export function generateMarkdownReport(
  result: ComparisonResult,
  selectedMismatches?: string[] // IDs of selected mismatches
): MarkdownReport {
  const { mismatches, metadata, similarity } = result;

  // Filter to selected mismatches if provided
  const targetMismatches = selectedMismatches
    ? mismatches.filter(m => selectedMismatches.includes(m.id))
    : mismatches;

  const screenInfo = metadata.screenName
    ? `**Screen**: ${metadata.screenName}\n`
    : "";

  const platformInfo = metadata.platform
    ? `**Platform**: ${metadata.platform}\n`
    : "";

  const content = `# UI Fidelity Issues

${screenInfo}${platformInfo}**Similarity Score**: ${similarity}%
**Date**: ${new Date(metadata.comparedAt).toLocaleString()}

---

## Mismatches Found (${targetMismatches.length})

${targetMismatches.map((m, idx) => `
### ${idx + 1}. ${m.title}

- **Category**: ${m.category}
- **Priority**: ${m.priority}
- **Location**: x:${m.bbox.x}, y:${m.bbox.y}, w:${m.bbox.width}, h:${m.bbox.height}

**Issue**: ${m.explanation}

**Fix**: ${m.suggestedFix}

---
`).join("\n")}

## How to Fix

1. Review each mismatch above
2. Use browser DevTools to inspect the element at the specified coordinates
3. Compare against the design mockup
4. Apply the suggested fixes
5. Re-run the comparison to verify

---

*Generated by UI Fidelity Checker on ${new Date(metadata.comparedAt).toLocaleDateString()}*
`;

  return { content };
}

/**
 * Generate JSON report
 */
export function generateJSONReport(result: ComparisonResult): JSONReport {
  return {
    version: "1.0.0",
    ...result,
  };
}

/**
 * Generate simplified checklist for UI display
 */
export function generateChecklistItems(mismatches: Mismatch[]): string[] {
  return mismatches.map(m => 
    `[${m.priority.toUpperCase()}] ${m.title} - ${m.category}`
  );
}

/**
 * Format mismatch for copy-paste
 */
export function formatMismatchForTicket(mismatch: Mismatch): string {
  return `
**${mismatch.title}** [${mismatch.priority}]

Category: ${mismatch.category}
Location: x:${mismatch.bbox.x}, y:${mismatch.bbox.y} (${mismatch.bbox.width}×${mismatch.bbox.height}px)

${mismatch.explanation}

**Action**: ${mismatch.suggestedFix}
`;
}
